# Generated by Django 3.1.3 on 2020-11-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_history', models.CharField(blank=True, default='', max_length=20)),
                ('repair_history', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'UsedCar',
            },
        ),
    ]
